# Generated by Django 2.2.5 on 2019-09-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('bronetime_start', models.DateTimeField(null=True)),
                ('bronetime_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkplace.Place')),
            ],
        ),
    ]
