# Generated by Django 2.2.5 on 2019-09-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei_code', models.CharField(max_length=255)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('bin_state', models.IntegerField(blank=True, null=True)),
                ('fire', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Device data',
                'verbose_name_plural': 'Device data',
            },
        ),
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei_code', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Device location',
                'verbose_name_plural': 'Device location',
            },
        ),
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_code', models.CharField(max_length=255)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('bin_state', models.IntegerField(blank=True, null=True)),
                ('fire', models.BooleanField(blank=True, null=True)),
                ('request_time', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
