# Generated by Django 2.2.5 on 2019-09-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0002_devicedata_devicesettings_logdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='imei_code',
            new_name='deviceName',
        ),
        migrations.RenameField(
            model_name='devicesettings',
            old_name='imei_code',
            new_name='deviceName',
        ),
        migrations.RenameField(
            model_name='logdata',
            old_name='imei_code',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='bin_state',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='fire',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='bin_state',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='fire',
        ),
        migrations.AddField(
            model_name='logdata',
            name='deviceName',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
