# Generated by Django 2.2.5 on 2019-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0003_auto_20190925_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='data',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
