# Generated by Django 2.2.5 on 2019-09-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0004_devicedata_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='data',
            new_name='general_data',
        ),
        migrations.RenameField(
            model_name='logdata',
            old_name='data',
            new_name='general_data',
        ),
    ]
