# Generated by Django 2.2.5 on 2019-09-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0005_auto_20190925_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='battery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='bin_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='fire',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='battery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='bin_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='fire',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
