# Generated by Django 2.2.5 on 2019-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0006_auto_20190927_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='bin_height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
