# Generated by Django 2.2.5 on 2019-09-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0007_devicesettings_bin_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='general_data',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='general_data',
        ),
    ]
