# Generated by Django 2.2.3 on 2019-11-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0008_auto_20190927_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Start point for bins',
                'verbose_name_plural': 'Start points for bins',
            },
        ),
        migrations.RemoveField(
            model_name='reserves',
            name='to_place',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Reserves',
        ),
    ]
