job 1:
  script:
    - 'cd /home/smart_bin_web/ && git fetch origin master && git reset --hard origin/master && .venv/bin/python manage.py makemigrations &&  .venv/bin/python manage.py migrate && .venv/bin/python manage.py collectstatic --no-input && .venv/bin/uwsgi parkin_uwsgi.ini'
